{% set name = "opentelemetry-instrumentation-urllib" %}
{% set version = "0.49b2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentelemetry_instrumentation_urllib-{{ version }}.tar.gz
  sha256: a148c073de6a1bbaf3ca423e639840cd2aa554eb0dda95077c111e46ea91d8ca

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
    - hatchling
  run:
    - python >=3.7
    - opentelemetry-api ~=1.12
    - opentelemetry-instrumentation ==0.49b2
    - opentelemetry-semantic-conventions ==0.49b2
    - opentelemetry-util-http ==0.49b2
    # - opentelemetry-test-utils ==0.37b0
    # - httpretty ~=1.0
    # - opentelemetry-test-utils ==0.38b0
    # - httpretty ~=1.0
    # - opentelemetry-test-utils ==0.39b0
    # - httpretty ~=1.0
    # - opentelemetry-test-utils ==0.40b0
    # - httpretty ~=1.0
    # - opentelemetry-test-utils ==0.41b0
    # - httpretty ~=1.0
    # - opentelemetry-test-utils ==0.42b0
    # - httpretty ~=1.0
    # - opentelemetry-test-utils ==0.43b0
    # - httpretty ~=1.0
    # - opentelemetry-test-utils ==0.44b0
    # - httpretty ~=1.0


test:
  imports:
    - opentelemetry
    - opentelemetry.instrumentation
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-urllib
  summary: OpenTelemetry urllib instrumentation
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mariusvniekerk
