{% set name = "opentelemetry-instrumentation-urllib" %}
{% set version = "0.53b0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/opentelemetry_instrumentation_urllib-{{ version }}.tar.gz
  sha256: 1cbbc161a5e2a6a268edce777eb766aae7de79f74b177669eb4f4a20e4cf2f7c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - opentelemetry-api ~=1.12
    - opentelemetry-instrumentation ==0.53b0
    - opentelemetry-semantic-conventions ==0.53b0
    - opentelemetry-util-http ==0.53b0
    # - opentelemetry-test-utils ==0.37b0
    # - httpretty ~=1.0
    # - opentelemetry-test-utils ==0.38b0
    # - httpretty ~=1.0
    # - opentelemetry-test-utils ==0.39b0
    # - httpretty ~=1.0
    # - opentelemetry-test-utils ==0.40b0
    # - httpretty ~=1.0
    # - opentelemetry-test-utils ==0.41b0
    # - httpretty ~=1.0
    # - opentelemetry-test-utils ==0.42b0
    # - httpretty ~=1.0
    # - opentelemetry-test-utils ==0.43b0
    # - httpretty ~=1.0
    # - opentelemetry-test-utils ==0.44b0
    # - httpretty ~=1.0


test:
  imports:
    - opentelemetry
    - opentelemetry.instrumentation
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-urllib
  summary: OpenTelemetry urllib instrumentation
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mariusvniekerk
