{% set name = "opentelemetry-instrumentation-urllib" %}
{% set version = "0.43b0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentelemetry_instrumentation_urllib-{{ version }}.tar.gz
  sha256: 501ca05a0ad4486344e22141a1f72d881ecd7154ffac9cb5981e164d7ad80f20

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
    - hatchling
  run:
    - python >=3.7
    - opentelemetry-api ~=1.12
    - opentelemetry-instrumentation ==0.43b0
    - opentelemetry-semantic-conventions ==0.43b0
    - opentelemetry-util-http ==0.43b0
    # - opentelemetry-test-utils ==0.37b0
    # - httpretty ~=1.0
    # - opentelemetry-test-utils ==0.38b0
    # - httpretty ~=1.0
    # - opentelemetry-test-utils ==0.39b0
    # - httpretty ~=1.0
    # - opentelemetry-test-utils ==0.40b0
    # - httpretty ~=1.0
    # - opentelemetry-test-utils ==0.41b0
    # - httpretty ~=1.0
    # - opentelemetry-test-utils ==0.42b0
    # - httpretty ~=1.0
    # - opentelemetry-test-utils ==0.43b0
    # - httpretty ~=1.0


test:
  imports:
    - opentelemetry
    - opentelemetry.instrumentation
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-urllib
  summary: OpenTelemetry urllib instrumentation
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mariusvniekerk
