{% set name = "opentelemetry-instrumentation-urllib" %}
{% set version = "0.55b1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/opentelemetry_instrumentation_urllib-{{ version }}.tar.gz
  sha256: 9961b6035cc68df048e703089de14da4e05e6f123a1f3d61c9341a2a75123a8d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - opentelemetry-api ~=1.12
    - opentelemetry-instrumentation ==0.55b1
    - opentelemetry-semantic-conventions ==0.55b1
    - opentelemetry-util-http ==0.55b1
    # - opentelemetry-test-utils ==0.37b0
    # - httpretty ~=1.0
    # - opentelemetry-test-utils ==0.38b0
    # - httpretty ~=1.0
    # - opentelemetry-test-utils ==0.39b0
    # - httpretty ~=1.0
    # - opentelemetry-test-utils ==0.40b0
    # - httpretty ~=1.0
    # - opentelemetry-test-utils ==0.41b0
    # - httpretty ~=1.0
    # - opentelemetry-test-utils ==0.42b0
    # - httpretty ~=1.0
    # - opentelemetry-test-utils ==0.43b0
    # - httpretty ~=1.0
    # - opentelemetry-test-utils ==0.44b0
    # - httpretty ~=1.0


test:
  imports:
    - opentelemetry
    - opentelemetry.instrumentation
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-urllib
  summary: OpenTelemetry urllib instrumentation
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mariusvniekerk
